[package]
name = "qiskit-c-ext"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "qiskit_c_ext"
doctest = false
crate-type = ["cdylib", "rlib"]

[dependencies]
num-complex.workspace = true
qiskit-accelerate.workspace = true

[build-dependencies]
cbindgen = "0.26"

[features]
default = ["cbinding"]
cbinding = []
