sys_includes = ["complex.h"]

after_includes = """
typedef float complex Complex32;
typedef double complex Complex64;

/// @defgroup sparse_observable_functions SparseObservable Functions
/// This is a group of functions for interacting with opaque SparseObservable instances.
"""

[parse]
parse_deps = true
include = ["qiskit-accelerate"]

[enum]
prefix_with_name = true
