sys_includes = ["complex.h"]

after_includes = """
typedef float complex Complex32;
typedef double complex Complex64;
"""

[parse]
parse_deps = true
include = ["qiskit-accelerate"]

[export]
include = ["CSparseObservable"]

[enum]
prefix_with_name = true
